### ISSUE TITLE
newbie ngrok http 5000

### ISSUE THREAD

**Issue by olivalcf** [progapandist/rubotnik#22]
Hey there, I might be missing a step, but when I launch ngrok 5000 I'm getting an error: 

> The connection to https://27548728.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:5000.
Make sure that a web service is running on localhost:5000 and that it is a valid address.
The error encountered was: dial tcp [::1]:5000: getsockopt: connection refused

not sure what to do

**Comment by olivalcf** [comment]
My bad, 
the issue isn't from ngrok but from heroku local I'm getting this error: 
`[OKAY] Loaded ENV .env File as KEY=VALUE Format
10:49:51 PM web.1 |  [11711] Puma starting in cluster mode...
10:49:51 PM web.1 |  [11711] * Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
10:49:51 PM web.1 |  [11711] * Min threads: 5, max threads: 5
10:49:51 PM web.1 |  [11711] * Environment: development
10:49:51 PM web.1 |  [11711] * Process workers: 1
10:49:51 PM web.1 |  [11711] * Preloading application
10:49:52 PM web.1 |  [11711] ! Unable to load application: Facebook::Messenger::Subscriptions::Error: An unknown error has occurred.
10:49:52 PM web.1 |  bundler: failed to load command: puma (/Users/oliv/.rbenv/versions/2.5.3/bin/puma)
10:49:52 PM web.1 |  Facebook::Messenger::Subscriptions::Error: An unknown error has occurred.
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/facebook-messenger-1.1.2/lib/facebook/messenger/subscriptions.rb:74:in `raise_errors'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/facebook-messenger-1.1.2/lib/facebook/messenger/subscriptions.rb:36:in `subscribe'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rubotnik-0.2.2/lib/rubotnik.rb:48:in `subscribe'
10:49:52 PM web.1 |    /Users/oliv/Desktop/sites/pollution-bot/bot/bot.rb:6:in `<top (required)>'
10:49:52 PM web.1 |    config.ru:5:in `require_relative'
10:49:52 PM web.1 |    config.ru:5:in `block in <main>'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
10:49:52 PM web.1 |    config.ru:in `new'
10:49:52 PM web.1 |    config.ru:in `<main>'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:410:in `run'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/bin/puma:23:in `load'
10:49:52 PM web.1 |    /Users/oliv/.rbenv/versions/2.5.3/bin/puma:23:in `<top (required)>'
[DONE] Killing all processes with signal  SIGINT
10:49:52 PM web.1 Exited with exit code null
`

**Comment by progapandist** [comment]
Glad you figured it out! 💪

**Comment by progapandist** [comment]
Make sure you have `puma` server installed on your machine and that `bundle install` also works to install all dependencies

**Comment by olivalcf** [comment]
Thanks for your support, seems like puma is installed but I'm getting a 

`Unable to load application: Facebook::Messenger::Subscriptions::Error: An active access token must be used to query information about the current user.`

**Comment by progapandist** [comment]
It seems that you haven't set up your Facebook dev account in a console, please follow instructions in a README. Might be, something has changed, as I haven't developed this project for a while, but normally you should have your token set up as an environment variable (inside `.env`).
