### ISSUE TITLE
Binding matches multiple commands

### ISSUE THREAD

**Issue by Bajena** [progapandist/rubotnik#6]
Hey,
I've noticed that if I setup a following set of bindings:
```ruby
  bind "say", "something", all: true do
    do_thing_1
  end

  bind "something" do
    do_thing_2
  end
```

rubotnik will fire both `do_thing_1` and `do_thing_2`. I think more natural behavior would be to handle only the first matched binding and stop processing.

**Comment by progapandist** [comment]
Hi! Thanks for bringing that to my attention, it indeed makes sense. Feel free to make a PR though! It may take me some time to get back to the codebase, so you if you have any time on your hands — I'll be grateful.
